### ISSUE TITLE
Remove DataFrames.jl dependency and implement the Tables.jl interface

### ISSUE THREAD

**Issue by juliohm** [tom-metherell/Mice.jl#11]
Thanks for this package! Would it be possible to remove DataFrames.jl and support any Tables.jl table instead?

I am asking it because then it would be much easier to integrate this package with other existing transforms for tables.

**Comment by tom-metherell** [comment]
Will do it ASAP :D

**Comment by juliohm** [comment]
Also, consider slimming down the plot deps and other deps that are not necessarily part of the core implementation. You can always use package extensions for additional functionality, or let other people write the extensions in other packages as well. :)

**Comment by tom-metherell** [comment]
That much is already done :)
